aria labels and roles
isunjn/serene pull request #53
Opened 2023-11-27 08:03 UTC by k-cross

This is to make a blog more a11y friendly by including more labels for things and fewer obstacles for visual elements that don't matter.

2023-11-27 13:32 UTC, isunjn requested changes

2023-11-27 13:32 UTC, isunjn commented on templates/_footer.html
> +<footer aria-label="Footer">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/_header.html
> +<header {% if config.extra.blur_effect %} class="blur" {% endif %} aria-label="Main Menu">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/_header.html
> +  <div id="header-wrapper" role="none">
i think there is no need to add role="none" to a div element

2023-11-27 13:32 UTC, isunjn commented on templates/_header.html
> +    <nav class="main-nav" role="none">
why add role="none" to a nav? the class is unnecessary too

2023-11-27 13:32 UTC, isunjn commented on templates/_header.html
> +    <div id="btns" aria-label="Options">
unnecessary, also i think "options" is a confused word there

2023-11-27 13:32 UTC, isunjn commented on templates/blog.html
> +<div id="wrapper" role="none">
no need

2023-11-27 13:32 UTC, isunjn commented on templates/blog.html
> +  <main class="layout-list" aria-label="Topics">
"topics" is a confused word here

2023-11-27 13:32 UTC, isunjn commented on templates/blog.html
> +    <div class="category" aria-label="Topic">{{ category }}</div>
same

2023-11-27 13:32 UTC, isunjn commented on templates/home.html
> +<div id="wrapper" role="none">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/home.html
> +  <main aria-label="Content Sections">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/home.html
> +      <div id="text" role="none">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/home.html
> +        <div role="none">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/home.html
> +        <div id="bio" aria-label="Blurb"> {{ config.extra.bio }} </div>
why not "bio"?

2023-11-27 13:32 UTC, isunjn commented on templates/home.html
> +      <div id="left" role="none">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/home.html
> +      <div id="right" role="none">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/home.html
> +      <section id="brief" class="prose" aria-label="About">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/post.html
> +<div id="wrapper" role="none">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/post.html
> +  <div id="blank" aria-hidden=true role="none"></div>
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/post.html
> +      <article class="prose" data-backlink-icon="{{ backlink_icon }}" aria-label="{{ page.title }}">
no need

2023-11-27 13:32 UTC, isunjn commented on templates/post.html
> +        <h1 role="none">{{ page.title }}</h1>
why?

2023-11-27 13:32 UTC, isunjn commented on templates/projects.html
> +<div id="wrapper" role="none">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/projects.html
> +  <main aria-label="Projects">
unnecessary

2023-11-27 13:32 UTC, isunjn commented on templates/projects.html
> +          <div role="none"><span role="none">#</span>{{ tag }}</div>
unnecessary

2023-11-27 17:39 UTC, k-cross commented
I'm definitely not an a11y pro but I thought a tree with more contextual information would be better for the vision impaired.

Current:
<img width="1085" alt="Screenshot 2023-11-27 at 09 33 13" src="https://github.com/isunjn/serene/assets/11242401/50779db5-d68d-4333-a27b-88cba658f6d0">

Branch:
<img width="1028" alt="Screenshot 2023-11-27 at 09 36 33" src="https://github.com/isunjn/serene/assets/11242401/99035971-02e8-41e8-975c-9198ba6809fb">

2023-11-28 10:10 UTC, isunjn commented
i'm not a pro either, i will take a closer look at a11y topics and then decide what to add, thanks for the pr anyway!

2023-11-28 17:16 UTC, k-cross commented
thanks for taking the time to look!

2023-12-23 17:54 UTC, isunjn commented
I took a brief look, and it seems like we should not give every node on a11y tree a name/label，what matters is controls, interactive/focusable elements.

The "contextual information" you added might actually be annoying/needless for the vision impaired.

Also the [firefox accessibility inspector](https://firefox-source-docs.mozilla.org/devtools-user/accessibility_inspector/) can tell you the a11y "issues" on your page，and seems the only noticable issue of this theme is color contrast problem, i plan to change the default primary color in future releases

2023-12-23 17:54 UTC, closed without merging

2024-01-30 07:22 UTC, k-cross commented
Sorry, I just noticed this in my inbox. Sorry for the noise.